import React, { useEffect, useState, useCallback } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { gql, useMutation } from '@apollo/client';
import { addAbortSignal } from 'stream';

import { data, fields, columns } from '../data/test/realgrid-data'
import { IRealGridProps } from '../interface/components/IRealGird'
import dynamic from 'next/dynamic'
import RealGrid from '../components/common/grid/realGrid'
import { withApollo } from '../libs/withApollo'

//const RealGrid = dynamic<IRealGridProps>(() => import('../components/common/grid/realGrid'), { ssr: false })

export const LOGIN_MUTATION = gql`
  mutation loginMutation($loginInput: LoginInput!) {
    login(input: $loginInput) {
      message
      flag
      status
      token
    }
  }
`
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-3xl font-bold underline">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>-----</div>
        <RealGrid
          gridTitle='aa'
          loading={false}
          id="realgrid2"
          fields={fields}
          columns={columns}
          rows={data}
        />
      </main>
    </>
  )
}

export default withApollo(Home)
